language: java
before_install:
  - chmod +x mvnw
addons:
    sonarcloud:
        organization: "loscalidosos2021"
        token:
            secure: 1cb90563935287a3a53d36863034df763f581175
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
